spring.datasource.url=jdbc:postgresql://ballast.proxy.rlwy.net:45472/railway
spring.datasource.username=postgres
spring.datasource.password=DKEbBnHbppvVWPcqTvBQYZbtpDODzWTD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false
spring.h2.console.enabled=false

app.jwt.secret=SudokuInfinityProdKey2024AbcDefGhiJklMnoPqrStuVwxYz123456789
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000

app.cors.allowed-origins=*

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=10m

server.port=8080
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
logging.level.com.sudokuinfinity=INFO
logging.level.org.springframework.security=WARN